client_project/config/routes.rb
Rails.application.routes.draw do

  root 'experiments#index'
resources :users
resources :experiments do
  resources :proposals
end
resources :comments
resources :observations


get 'admin', :to => "sessions#index"
get 'login', :to => "sessions#login"
get "/experiments/:id/logs/new", :to => "logs#new", as: 'new_log'
post "/experiments/:id/logs", :to => "logs#create"
get "/experiments/:id/users/new", :to => "experiments#users"

# get 'students' :to => "sessions#index"
#go to the same place, redirect to different pages, with before_actions to prevent
# access unless you belonged...login page needs to be homepage, directs based on login...
# then our admin page will be locked to admin only...students will be open to all

match ':controller(/:action(/:id))', :via => [:get, :post]

end

client_project/app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_many :researcher_experiments, foreign_key: "experiment_id"
  has_many :researchers, through: :researcher_experiments
  has_many :observations
  has_one :proposal
  has_many :procedures
  has_many :lab_tasks, through: :procedures
  has_many :logs


end

client_project/app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  before_action :confirm_logged_in

  def index
    @users = User.all
    @experiments = Experiment.all
    @experiment = Experiment.new
  end

  def show
    @experiment = Experiment.find(params[:id])
  end

  def new
    @experiment = Experiment.new
  end

  def edit
    @experiment = Experiment.new
  end

  def create
    debugger
    p experiment_params[:procedures]
    @experiment = Experiment.create( title: experiment_params[:title], problem:experiment_params[:problem], hypothesis: experiment_params[:hypothesis], materials: experiment_params[:materials], results: experiment_params[:result], conclusion: experiment_params[:conclusion], active: experiment_params[:active], start_date:experiment_params[:start_date], end_date:experiment_params[:end_date], grad_hour_budget: experiment_params[:grad_hour_budget].to_i)
    proposal = Proposal.create(experiment_id: @experiment.id, abstract: experiment_params[:abstract], proposed_funding: experiment_params[:proposed_funding])
    @experiment.proposal = proposal
    procedures = experiment_params[:procedures]
    procedures_array = []
    procedures.each do |procedure_text|
      p = Procedure.create(text: procedure_text, experiment_id: @experiment.id)
       procedures_array << p
    end
    @experiment.procedures = procedures_array
    @experiment.save
    redirect_to experiment_path(@experiment)
  end

  def users
    @users = User.all
    @users = @users.sort_by(&:last_name)
  end


  private
  def experiment_params
    params.require(:experiment).permit(:observation, :title, :problem, :hypothesis, :materials, :result, :conclusion, :active, :abstract, :proposed_funding, :start_date, :end_date, :grad_hour_budget, :procedures => [])
  end

end

client_project/app/helpers/experiments_helper.rb
module ExperimentsHelper

  def summed_log_hours
    sum = 0
     @experiment.logs.each do |log|
        sum += log.hours_worked
    end
    sum
  end

end

client_project/app/views/experiments/edit.html.erb
<div class="experiment_container">
  <h1>Edit Experiment</h1>
    <%= form_for :experiment, url: experiments_path do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :problem %><br>
        <%= f.text_area :problem %>
      </p>
      <p>
        <%= f.label :hypothesis %><br>
        <%= f.text_area :hypothesis %>
      </p>
      <p>
        <%= f.label :materials %><br>
        <%= f.text_area :materials %>
      </p>
      <p>
        <%= f.label :procedure %><br>
        <%= f.text_area :procedure %>
      </p>
      <p>
        <%= f.label :results %><br>
        <%= f.text_area :results %>
      </p>
      <p>
        <%= f.label :conclusion %><br>
        <%= f.text_area :conclusion %>
      </p>
      <div>
        <b><%= label :active, "Active:" %></b>
        <%= label :active, "Yes" %>
        <%= f.radio_button :access_rights, false , :checked => true , :value => false %>
        <%= label :active, "No" %>
        <%= f.radio_button :access_rights, false , :checked => true , :value => false %>
      </div>

      <p>
        <%= f.label :start_date %><br>
        <%= f.date_field :start_date %>
      </p>
      <p>
        <%= f.label :end_date %><br>
        <%= f.date_field :end_date %>
      </p>

      <p>
        <%= f.submit %>
      </p>
    <% end %>
</div>

client_project/app/views/experiments/index.html.erb
<h1>Experiments</h1>
  <div class="experiment_list">
    <% if @experiments %>
      <ul>
        <% @experiments.each do |experiment| %>
          <li>
            <%= link_to "#{experiment.title}", experiment_path(experiment) %>
          </li>
        <% end%>
      </ul>
    <%end%>
  </div>

<% if admin? %>
  <h3><a href="/experiments/new">Create New Experiment</a></h3>
<% end %>

client_project/app/views/experiments/new.html.erb
<div class="experiment_container">
  <h1>Create Experiment</h1>
    <%= form_for :experiment, url: experiments_path do |f| %>
      <p>
        <%= f.label :"grad hour budget" %><br>
        <%= f.text_field :grad_hour_budget %>
      </p>
      <p>
        <%= f.label :proposed_funding %><br>
        <%= f.text_field :proposed_funding %>
      </p>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :abstract %><br>
        <%= f.text_area :abstract %>
      </p>
      <p>
        <%= f.label :problem %><br>
        <%= f.text_area :problem %>
      </p>
      <p>
        <%= f.label :hypothesis %><br>
        <%= f.text_area :hypothesis %>
      </p>
      <p>
        <%= f.label :materials %><br>
        <%= f.text_area :materials %>
      </p>
      <p id="procedure_input">
        <%= f.label :procedures %><br>
        <textarea name="experiment[procedures][]" id="experiment_procedure"></textarea>
      </p>
      <button id="procedure_button">new procedure</button>
      <p>
        <%= f.label :results %><br>
        <%= f.text_area :results %>
      </p>
      <p>
        <%= f.label :conclusion %><br>
        <%= f.text_area :conclusion %>
      </p>
      <div>
        <b><%= label :active, "Active:" %></b>
        <%= label :active, "Yes" %>
        <%= f.radio_button :active, false , :checked => true , :value => false %>
        <%= label :active, "No" %>
        <%= f.radio_button :active, false , :checked => true , :value => false %>
      </div>

      <p>
        <%= f.label :start_date %><br>
        <%= f.date_field :start_date %>
      </p>
      <p>
        <%= f.label :end_date %><br>
        <%= f.date_field :end_date %>
      </p>

      <p>
        <%= f.submit %>
      </p>
    <% end %>
</div>

client_project/app/views/experiments/show.html.erb
<div class="experiment_show_container">
  <div class="exp_title">
    <h1>Experiment: <%= @experiment.title %></h1>
  </div>
    <ul>
      <li>
        <label class="exp_header">Problem:</label> <%= @experiment.problem %>
      </li><br>
       <li>
       <label class="exp_header">Proposal:</label> <%= @experiment.proposal.abstract %>
      </li><br>
      <li>
        <label class="exp_header">Hypothesis:</label> <%= @experiment.hypothesis %>
      </li><br>
      <li>
        <label class="exp_header">Materials:</label> <%= @experiment.materials %>
      </li><br>
      <li>
        <label class="exp_header">Procedures:</label>
        <ol>
        <%@experiment.procedures.each do |procedure| %>
          <li><%= procedure.text %></li>
          <% end %>
        </ol>
      </li><br>
      <li>
        <label class="exp_header">Results:</label> <%= @experiment.results %>
      </li><br>
      <li>
        <label class="exp_header">Conclusion:</label> <%= @experiment.conclusion %>
      </li><br>
      <li>
        <label class="exp_header">Active:</label> <%= @experiment.active %>
      </li><br>
      <li>
        <label class="exp_header">Begin date:</label> <%= @experiment.start_date.strftime("%m/%d/%Y") %>
      </li><br>
      <li>
        <label class="exp_header">End date:</label> <%= @experiment.end_date.strftime("%m/%d/%Y") %>
      </li><br>
      <li>
        <label class="exp_header">Grad Hour Budget:</label> <%= summed_log_hours %> out of <%= @experiment.grad_hour_budget %> hours worked.
      </li><br>
      <% if admin? %>
        <center><span class="exp_header"><%= link_to "Edit Current Experiment", edit_experiment_path(@experiment) %></span></center>
      <% end %>
      <li>
      </li>
      <li>
      </li>
      <div id="researcher_container">
        <h3 class="exp_header"> Researchers: </h3>
        <ul>
        <% @experiment.researchers.each do |researcher| %>
          <li id="researcher_name"><%= link_to "#{researcher.first_name} #{researcher.last_name}", user_path(researcher) %></li>
        <% end %>
        </ul>
      </div>
      <% if admin? %>
        <center><span class="exp_header"><a href="/experiments/<%= @experiment.id %>/users/new">Add New Researcher</a></span></center>
      <% end %>
    <div id="content">
      <% @experiment.logs.each do |log| %>
      <div id = "log">
        <h4 id="observation"> Observation: <%= log.observation.title %></h4>
        <p id="observer_name">name: <%="#{log.user.first_name} #{log.user.last_name}"%></p>
        <p id="observer_name">hours logged: <%= log.hours_worked %></p>
          <div id="procedure_task">
              <ol>
             <% @experiment.procedures.each do |experiment_procedure| %>
               <li><%= experiment_procedure.text%>
                <% if log.procedures.include?(experiment_procedure)%>
                  <i class="tiny material-icons cyan">done</i></li>
             <% end %>
         <% end %>
              </ol>
          </div>
        </div>
      <% end %>
  </div>
</div>

<% if admin? || current_user.experiments.any? {|experiment| experiment.id} %>
  <center>
    <div class="new_log_form">
      <span class="exp_header"><a href="/experiments/<%= @experiment.id %>/logs/new">Create New Log</a></span>
    </div>
  </center>
<% end %>

client_project/app/views/experiments/users.html.erb
<h2> List of Researchers </h2>
<% @users.each do |user| %>
  <li class= "draggable" ><%=user.first_name + " " + user.last_name + ": " + user.email %></li>
  <% end %>