client_project/config/routes.rb
Rails.application.routes.draw do

  root 'experiments#index'
resources :users
resources :experiments do
  resources :proposals
end
resources :comments
resources :observations


get 'admin', :to => "sessions#index"
get 'login', :to => "sessions#login"
get "/experiments/:id/logs/new", :to => "logs#new", as: 'new_log'
post "/experiments/:id/logs", :to => "logs#create"
get "/experiments/:id/users/new", :to => "experiments#users"

# get 'students' :to => "sessions#index"
#go to the same place, redirect to different pages, with before_actions to prevent
# access unless you belonged...login page needs to be homepage, directs based on login...
# then our admin page will be locked to admin only...students will be open to all

match ':controller(/:action(/:id))', :via => [:get, :post]

end

client_project/app/models/user.rb
class User < ActiveRecord::Base
  has_many :researcher_experiments, foreign_key: "researcher_id"
  has_many :experiments, through: :researcher_experiments
  has_many :comments
  has_many :observations
  has_many :logs

  has_secure_password

end

client_project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to(:controller => 'experiments', :action => 'index')
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    admin_key = user_params[:admin_key]
    @user = User.new(first_name: user_params[:first_name], last_name: user_params[:last_name], email: user_params[:email], password: user_params[:password])
    if admin_key == "papyrus"
      @user.admin = true
    else
      @user.admin = false
    end
      @user.save
    session[:user_id] = @user.id
    redirect_to @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if(@user.update(user_params))
      redirect_to user_path(@user)
    else
      render('edit')
    end
  end



  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin_key)
  end

end

client_project/app/helpers/users_helper.rb
module UsersHelper
end

client_project/app/views/users/edit.html.erb
<h1>Edit User</h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :admin,     as: :radio_buttons %>
    <%= f.button :submit %>
  <% end %>

client_project/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

client_project/app/views/users/new.html.erb
<div class="create_user_container">
  <h1>Create User</h1>
    <%= form_for @user, url: users_path(@user) do |f| %>
      <p>
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
      </p>
      <p>
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
      </p>
      <p>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :admin_key%><br>
        <%= f.password_field :admin_key%>
      </p>
      <p>
        <%= f.submit ("Create User") %>
      </p>
    <% end %>
</div>

client_project/app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<ul>
    <% if @user.admin %>
  <li>
    <h2> Administrator</h2>
  </li>
    <% end %>
  <li>
    <%= "#{@user.first_name} #{@user.last_name}" %>
  </li>
  <li>
    <%= @user.email %>
  </li>
  <h3> Research </h3>
  <% @user.experiments.each do |experiment| %>
    <%= link_to experiment.title, experiment_path(experiment) %>
  <% end %>
  <br><br><%= link_to "Edit Profile Information", edit_user_path(@user) %>
</ul>